=== grechaw/grip/src/main/xquery/app/resources/schemas/marklogic/mimetypes.xsd
<!-- Copyright 2002-2011 MarkLogic Corporation.  All Rights Reserved. -->
<xs:schema targetNamespace="http://marklogic.com/xdmp/mimetypes"
 xsi:schemaLocation="http://www.w3.org/2001/XMLSchema XMLSchema.xsd
                     http://www.w3.org/1999/xhtml xhtml-inlstyle-1.xsd"
 xmlns="http://marklogic.com/xdmp/mimetypes"
 xmlns:admin="http://marklogic.com/xdmp/admin"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xhtml="http://www.w3.org/1999/xhtml">

  <xs:annotation>
    <xs:documentation>
      Mimetype schema.
    </xs:documentation>
  </xs:annotation>

  <xs:simpleType name="name">
    <xs:annotation>
      <xs:documentation>
        A content type name.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:token">
      <xs:pattern value="[0-9A-Za-z.+-]+/[0-9A-Za-z.+-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="name" type="name">
    <xs:annotation>
      <xs:documentation>
        A content type name.
      </xs:documentation>
      <xs:appinfo>
        <admin:help xmlns="http://www.w3.org/1999/xhtml">
          <span class="help-text"><span style="color:#800000">name</span> 
          specifies the MIME type.</span>
        </admin:help>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>

  <xs:simpleType name="extension">
    <xs:annotation>
      <xs:documentation>
        A file extension.
      </xs:documentation>
    </xs:annotation>
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="[a-z0-9]*"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="if-not-found!"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="extensions">
    <xs:annotation>
      <xs:documentation>
        The file extensions.
      </xs:documentation>
    </xs:annotation>
    <xs:list itemType="extension"/>    
  </xs:simpleType>

  <xs:element name="extensions" type="extensions">
    <xs:annotation>
      <xs:documentation>
        The file extensions.
      </xs:documentation>
      <xs:appinfo>
        <admin:help xmlns="http://www.w3.org/1999/xhtml">
          <span class="help-text"><span style="color:#800000">extensions</span> 
          specifies a comma-separated list of file name extensions.</span>
        </admin:help>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>

  <xs:simpleType name="format">
    <xs:annotation>
      <xs:documentation>
        The file format in the database.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="xml"/>
      <xs:enumeration value="text"/>
      <xs:enumeration value="binary"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="format" type="format">
    <xs:annotation>
      <xs:documentation>
        The file format in the database.
      </xs:documentation>
      <xs:appinfo>
        <admin:help xmlns="http://www.w3.org/1999/xhtml">
          <span class="help-text"><span style="color:#800000">format</span> 
            specifies the default format for loading documents with URIs 
            ending in the specified MIME file extension. Documents with 
            URIs ending with the file extension are loaded as the specified 
            format (XML, binary, or text), unless an explicit format is 
            specified in the load command. For example, if the xml file 
            extension is set to XML format, then loading a document with a URI 
            <code>http://marklogic.com/file.xml</code> will result in loading 
            an XML document. </span>
        </admin:help>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>

  <xs:complexType name="mimetype">
    <xs:annotation>
      <xs:documentation>
        A MIME type specification.
      </xs:documentation>
      <xs:appinfo>
      </xs:appinfo>
    </xs:annotation>
    <xs:all>
      <xs:element ref="name"/>
      <xs:element ref="extensions"/>
      <xs:element ref="format"/>
    </xs:all>
  </xs:complexType>

  <xs:element name="mimetype" type="mimetype">
    <xs:annotation>
      <xs:documentation>
        A MIME type specification.
      </xs:documentation>
      <xs:appinfo>
        <admin:help xmlns="http://www.w3.org/1999/xhtml">
          <hr class="control-line" size="1"/><br/>
          <span class="help-text">
          <img src="images/varspace.gif" alt="" width="20" height="1"
          />Mimetypes Configuration Help<br/><br/>
          </span>
          <hr class="control-line" size="1"/>
          <span class="help-text"><p>The MIME types configuration governs the 
          mapping of file type extensions to MIME types. These mimetype
          extensions set up default formats for documents with a given
          URI extension.</p>
          <p>Each <span style="color:#800000">mimetype</span> specifies a MIME
          type for a set of file extensions:</p></span>
        </admin:help>
        <admin:help xmlns="http://www.w3.org/1999/xhtml">
          <hr class="control-line" size="1"/>
          <span class="help-text"><p>Buttons and Tabs:</p></span>
          <ul>
	    <li><span class="help-text">The 
            <span style="color:#800000">delete</span> 
            button deletes the mimetype permanently. </span></li>
	    <li><span class="help-text">Click the 
            <span style="color:#800000">create</span> tab to enter new mimetype
            definitions. </span></li>
          </ul>
        </admin:help>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>

  <xs:complexType name="mimetypes">
    <xs:annotation>
      <xs:documentation>
        The MIME type specifications.
      </xs:documentation>
      <xs:appinfo>
      </xs:appinfo>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="mimetype"/>
    </xs:choice>
  </xs:complexType>

  <xs:element name="mimetypes" type="mimetypes">
    <xs:annotation>
      <xs:documentation>
        The MIME type specifications.
      </xs:documentation>
      <xs:appinfo>
      </xs:appinfo>
    </xs:annotation>
  </xs:element>
  
</xs:schema>

=== grechaw/grip/src/main/xquery/app/resources/config/mimetypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mimetypes xmlns="http://marklogic.com/xdmp/mimetypes"
	 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="../schemas/mimetypes.xsd">
	<mimetype>
		<name>text/html</name>
		<extensions>html htm</extensions>
		<format>text</format>
	</mimetype>
	<mimetype>
		<name>text/plain</name>
		<extensions>nt</extensions>
		<format>text</format>
	</mimetype>
	<mimetype>
		<name>text/turtle</name>
		<extensions>ttl</extensions>
		<format>text</format>
	</mimetype>
	<mimetype>
		<name>application/rdf+xml</name>
		<extensions>rdf</extensions>
		<format>xml</format>
	</mimetype>
	<mimetype>
		<name>application/sparql-result+xml</name>
		<extensions>sr</extensions>
		<format>xml</format>
	</mimetype>
	<mimetype>
		<name>application/trix+xml</name>
		<extensions>trix</extensions>
		<format>xml</format>
	</mimetype>
	<mimetype>
		<name>application/wadl+xml</name>
		<extensions>wadl</extensions>
		<format>xml</format>
	</mimetype>
	<mimetype>
		<name>application/xml</name>
		<extensions>xml</extensions>
		<format>xml</format>
	</mimetype>
</mimetypes>
